# Data config
DATA_COLS: ['date','store','item','sales']
CATEGORIES: ['store','item']
NUMERIC_COLS: ['store','item','sales']
GROUPED_COLS: ['store','item','date']
LABEL_COL: sales
INDEX_COL: date


# Model Parameters
# LSTM
LSTM_PARAMS:
  # Look back does not include current day, ie for 90 days of historic data lookback = 89
  LSTM_LOOKBACK: 89
  LSTM_PREDICTION_LAG: 90
  LSTM_EVAL_LEN: 360
  LSTM_NODES: 64
  LSTM_DROPOUT: 0.5
  LSTM_EPOCHS: 10
  LSTM_BATCH_SIZE: 90
  LSTM_LR: 0.01
  LSTM_LABEL_COUNT: 1

# XGBoost
XGB_PARAMS:
  XGB_MAX_DEPTH: 3
  XGB_ETA: 0.2
  XGB_SILENT: 1
  XGB_SUBSAMPLE: 1
  XGB_NUM_ROUNDS: 1000